[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python build complete - no Docker needed'"]

[start]
cmd = "python start_railway.py"
