[build]
builder = "NIXPACKS"
dockerfilePath = ""

[deploy]
startCommand = "python start_railway.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
